language: node_js

dist: bionic

node_js:
  - latest

install:
  - npm install

script: npm run cover

after_success: "sbt coveralls"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  email:
    recipients:
      - s.campos@qairadrones.com


# jobs:
#   include:
#     - stage: Produce Coverage
#       node_js: node
#       script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js