
language: node_js

dist: bionic

node_js:
  - node

include:
  - stage: 'Fundamental build'
  name: 'Unit tests'
  script: npm run test:coveralls

after_success: "sbt coveralls"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  email:
    recipients:
      - s.campos@qairadrones.com

