
language: node_js

dist: bionic

node_js:
  - node

install:
  - npm install

script: npm run test:coveralls

after_success: "sbt coveralls"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  email:
    recipients:
      - s.campos@qairadrones.com

