
language: node_js

dist: bionic

node_js:
  - node

install:
  - npm install
script: npm test
script: npm run test:coveralls
after_script: npm run cover

after_success: "sbt coveralls"

env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  email:
    recipients:
      - s.campos@qairadrones.com


# jobs:
#   include:
#     - stage: Produce Coverage
#       node_js: node
#       script: jest --coverage && cat ./tests/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage